sudo: required
dist: trusty

# Preparation: non-zero generates build error
before_install:
  - chmod +x -R bin/

# Initializes terraform workspace
install:
  - . bin/install.sh

# Validation, rollout and test: non-zero generates build failure
script:
  - . bin/build.sh
  - . bin/test.sh
  - . bin/commit.sh

# By this time, the build is a success/failure/error
