sudo: required
dist: trusty

# Preparation
before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  - unzip terraform_0.11.8_linux_amd64.zip

# Validation
script:
  - ./terraform init
  - ./terraform plan

# Roll out
deploy:
- provider: script
  script: 
    - ./terraform apply -auto-approve
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Autocommit - IaC state changed."
  - git push --quiet
